### ISSUE TITLE
Error creating project for vSphere infrastructure

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry-community/cyoi#32]
get this error when generating a vpshere project.

/usr/local/lib/ruby/gems/2.2.0/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:22:in `setup_credentials': undefined local variable or method `h1' for #<Cyoi::Cli::Providers::ProviderCliVsphere:0x00558d8b5e97c8> (NameError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/cyoi-0.11.3/lib/cyoi/cli/providers/provider_cli_vsphere.rb:6:in `perform_and_return_attributes'
	from /usr/local/lib/ruby/gems/2.2.0/gems/cyoi-0.11.3/lib/cyoi/cli/provider.rb:18:in `execute!'

    credentials["vsphere_server"] = hl.ask("Server: ").to_s unless credentials.exists?("vsphere_server")
    credentials["vsphere_expected_pubkey_hash"] = hl.ask("Expected public key hash: ").to_s unless credentials.exists?("vsphere_expected_pubkey_hash")

2nd line here uses h1 with a lower-case L

**Comment by phopper-pivotal** [comment]
looks like its been fixed but not in respects to gem install cyoi - still uses hl instead of h1.
